### ISSUE TITLE
notifications with urgency setting

### ISSUE THREAD

**Issue by pirateland** [eonpatapon/mpDris2#106]
By default mpDris2 pushes with medium urgency, but I think it would be nice (especially for people with a certain rice) to be able to set the urgency for the notifications.
The line for setting the urgency is easy (see below), but since it would require to add another configuration option (something like `notify_urgency`.
x is 0 for low, 1 for medium and 2 for high.
`self._notification.set_urgency(x)`

**Comment by eonpatapon** [comment]
Can you propose a patch for this ?

**Comment by pirateland** [comment]
See #108
