### ISSUE TITLE
Feature request: option to disable "MPD Notification" line in notification

### ISSUE THREAD

**Issue by mxmilkb** [eonpatapon/mpDris2#117]
Would be nice.

**Comment by grawity** [comment]
Which notifications are you referring to? Do you have a screenshot with this specific line?

**Comment by mxmilkb** [comment]
Using [mako](https://github.com/emersion/mako).

![rose_2019-03-15-06:31:33](https://user-images.githubusercontent.com/108225/54412936-306a2680-46ec-11e9-88a9-c82fcd04928c.png)

If I also enable the notifications offered in Cantata;

![rose_2019-03-15-06:32:21](https://user-images.githubusercontent.com/108225/54412977-5099e580-46ec-11e9-9f0a-f582ef891a8f.png)

**Comment by grawity** [comment]
Are you sure that's mpDris2 and not [mpd-notification](https://github.com/eworm-de/mpd-notification)?

**Comment by mxmilkb** [comment]
Aw jeez, yes, I also had that enabled. Thanks you the assistance.
