### ISSUE TITLE
Error starting mpDris2 (git) on Ubuntu 19.04

### ISSUE THREAD

**Issue by vaskark** [eonpatapon/mpDris2#121]
I'm getting this error from the latest git:

```
Traceback (most recent call last):
  File "/usr/local/bin/mpDris2", line 31, in <module>
    import mpd
ModuleNotFoundError: No module named 'mpd'
```
mpd is working fine otherwise (0.21.4 from Ubuntu 19.04 repo)
mpDris2 from repo is not working either. Although it was until recently.

Can someone help? Thanks.

**Comment by grawity** [comment]
Make sure you have either `python-mpd` (for Python 2) or `python3-mpd` (for Python 3) installed.

**Comment by vaskark** [comment]
@grawity That did it.
Many thanks. It was a stupid mistake, really. When I uninstalled the mpdris2 deb I did notice a python package being removed as well.
Apologies.
