### ISSUE TITLE
Missing file po/Makefile.in

### ISSUE THREAD

**Issue by DanySpin97** [eonpatapon/mpDris2#126]
The file is listed in configure.ac but it is missing since tag 0.6, making autotools fail.

EDIT: relevant output of configure.ac:
```
configure: creating ./config.status
config.status: creating Makefile
config.status: creating src/Makefile
config.status: error: cannot find input file: `po/Makefile.in.in'
```

**Comment by eonpatapon** [comment]
You need to run `intltoolize -f` first

**Comment by eonpatapon** [comment]
Actually you maybe just miss intltool in your environment ?

**Comment by DanySpin97** [comment]
I see. The autogen.sh my distribution ship and uses for building packages does not call intltoolize, so that was the issue. Thank you for your answer!
