### ISSUE TITLE
Empty value for album artist

### ISSUE THREAD

**Issue by lhupitr** [eonpatapon/mpDris2#144]
mpDris2 doesn't seem to be able to return the album artist (xesam:albumArtist):

> playerctl --player mpd metadata  
> mpd   xesam:album
> mpd   xesam:title      
> mpd   mpris:trackid   
> mpd   mpris:length   
> mpd   xesam:contentCreated 
> mpd   xesam:trackNumber   
> mpd   xesam:discNumber   
> mpd   xesam:artist    
> mpd   xesam:url

**Comment by eonpatapon** [comment]
Are you sure your file has this metadata ? mpDris2 should expose it if it's in the correct format (list of strings I believe) https://github.com/eonpatapon/mpDris2/blob/master/src/mpDris2.in.py#L113 https://github.com/eonpatapon/mpDris2/blob/master/src/mpDris2.in.py#L577

**Comment by lhupitr** [comment]
Yes, it works for example with mpd-mpris (incidentally it also returns 'genre' which  doesn't seem to be  returned by mpDris2 either)

**Comment by grawity** [comment]
I've added genre and albumArtist, but… I don't actually have mpd set up anywhere at the moment, so please test.

**Comment by lhupitr** [comment]
That works for me, thankyou.
