### ISSUE TITLE
Autostard mpDris2 scripts

### ISSUE THREAD

**Issue by inglor** [eonpatapon/mpDris2#42]
As mentioned [here](https://github.com/eonpatapon/mpDris2/issues/41) it would be good to have a mpDris2.service for systemd user integration like the below:
```
Description=Enabling mpDris2

[Service]
Type=dbus
ExecStart=mpDris2
```
or have information about how to start it from xdg autostart on the README.md

**Comment by smcv** [comment]
> Take a look at sofar/user-session-units. It has the DBus session stuff, and even a patch for dbus-daemon to fix broken activation.

Please prefer to use the D-Bus user bus units that are where they belong: in D-Bus (since 1.9.x). On Debian derivatives that's the dbus-user-session binary package.

**Comment by grawity** [comment]
Ok, this took a while. 46e2dce343eaa7fa32e920da625b66417272502f
