### ISSUE TITLE
Add support for KDE desktop

### ISSUE THREAD

**Issue by pashazz** [eonpatapon/mpDris2#61]
I mean multimedia hotkeys support in KDE. This is just a feature request

**Comment by lavacano201014** [comment]
As of Plasma 5.4 and KDE Apps 15.08 (not sure which is relevant) on Gentoo ~amd64, the "Media Player" plasmoid (are we still calling them plasmoids?) comes default with the desktop, and "just works" with mpDris2. Hotkeys are also present.

Unless the project intends to also support KDE 4, I'd say it's time to close this
