### ISSUE TITLE
Use of deprecated pygobject imports?

### ISSUE THREAD

**Issue by ff2000** [eonpatapon/mpDris2#62]
I have issues starting mpDris2.
`import glib` does not work. The new (?) and recommended way seems to be

    from gi.repository import GLib

If I add " as glib" everything works.
Until I enable Bling.notify. It does not find pynotify.
Again, the same game

    from gi.repository import Notify as pynotify

And here my python skills (and time ;)) ends:

```
Traceback (most recent call last):
  File "/usr/bin/mpDris2", line 1224, in <module>
    notification = Notify(params)
  File "/usr/bin/mpDris2", line 764, in __init__
    self._notification = pynotify.Notification("", "", "")
TypeError: GObject.__init__() takes exactly 0 arguments (3 given)
```

It seems Notify is not backwards compatible.
I am running pygobject-3.14.0 on Gentoo.

**Comment by grawity** [comment]
> `import glib` does not work. The new (?) and recommended way seems to be

>     from gi.repository import GLib

While pygobject 2.x is deprecated, it is still usable and can be installed side-by-side with pygobject 3.x (I think Gentoo calls it "slots"?)

Anyway, mpDris2-git will now use the best available version.

> It seems Notify is not backwards compatible.

"Backwards"? It's a completely different thing from pynotify, it was never meant to be compatible.

I'll try to port mpDris2 away from pynotify; until then, install `dev-python/py-notify`.

**Comment by grawity** [comment]
Ported to GObject.Notify in git.

**Comment by ff2000** [comment]
Thanks for the fixes!
I already tried py-notify, but it seems to offer yet another API for notifications. There is no pynotify import, you have to import "notify.all" or similar, according to the docs. That's why I thought it's the old way to import notify, just like "glib".
So never mind, everything is going fine now :)

**Comment by grawity** [comment]
Ah, it might be `dev-python/notify-python` in that case.
