### ISSUE TITLE
mpd skips songs when seeking through mpDris2

### ISSUE THREAD

**Issue by ff2000** [eonpatapon/mpDris2#63]
I use KDE and its media controller applet. When I seek through that applet mpd skips every song in the playlist (after finishing the current song) and right away continues with the last song in the playlist.
The issue then remains: starting the playlist will always jump to the last item in the playlist.
NOTE: I can see that every single item in the PL gets selected, until it reaches the last one. So it looks like someone notices a "run_next" command, and reacts on that by triggering itself "run_next" until there is no more "next" item.
As soon as I stop the mpDris2 service the behaviour sets back to normal.
I checked with cantata mpd client (which offers an own mpris2-interface) that the issue does not come from the kde applet. And indeed seeking through the applet does not trigger this issue.

**Comment by grawity** [comment]
Could you post the output of `mpDris2 --debug` when that happens?

Also, which version is being used? Does it still happen with latest git build?

**Comment by ff2000** [comment]
https://gist.github.com/anonymous/f34db2c44c753158b298

What I did:
* started mpd -> played track 1
* started mpDris2
* used ncmpcpp to seek right at the end of track 1
* mpd started playing track 2 just fine
* used plasma media controller to seek
* seeked further with ncmpcpp
* I saw in ncmpcpp that track 3 ("Urlicht") got highlighted, but it right away jumped to track 4 ("O glaube, mein Herz")

**Comment by ff2000** [comment]
Just wanted to note that kde applet (plasma5 - didn't mention that yet) is involved. I tried different applets/clients while not running kde, and none had issues with mpDris2. As cantata works fine it's either an issue with the combination kde<>mpDris2 or cantata adds hacks to workaround issues with the plasma applet ;)
As I don't use KDE anymore this issue has resovled itself. Feel free to close it.
