### ISSUE TITLE
CanGoNext returns false even if it "can go next"

### ISSUE THREAD

**Issue by subfusc** [eonpatapon/mpDris2#65]
### Error:
mpDris tells me that it can't go to next song even though it works sending Next to the MediaPlayer2 object on dbus. (see Example using qdbus)

### Expected result:
that mpDris should tell me that i can go to the next song if there is one. 

### Setup:
I'm running a mopidy mpd service on my local LAN and connected mpDris2 to it. 

### Versions:
OS: Fedora 22
Mopidy: 1.0.5
mpDris2: 0.4 (From fedora 22 repo) and current master (6295aa9f)
python: 2.7
python-mpd: 0.2.1 (from fedora 22 repo) and current master using python-mpd2 (eccee96f)

### Example:

```SH
$ qdbus org.mpris.MediaPlayer2.mpd /org/mpris/MediaPlayer2 org.mpris.MediaPlayer2.Player.Metadata
xesam:title: Bad Day
...

$ qdbus org.mpris.MediaPlayer2.mpd /org/mpris/MediaPlayer2 org.mpris.MediaPlayer2.Player.CanGoNext
false

$ qdbus org.mpris.MediaPlayer2.mpd /org/mpris/MediaPlayer2 org.mpris.MediaPlayer2.Player.Next

$ qdbus org.mpris.MediaPlayer2.mpd /org/mpris/MediaPlayer2 org.mpris.MediaPlayer2.Player.Metadata
xesam:title: Running To The Sea
...
```

**Comment by grawity** [comment]
The current CanGoNext() implementation returns true if the server gave us a `nextsongid` in reply to a `status` query. Does mopidy do that?

**Comment by subfusc** [comment]
No, it gives me this (printed directly out of MPDWrapper._update_properties()):

```python
{'songid': '17', 'playlistlength': '34', 'playlist': '11', 'repeat': '1', 'consume': '0', 'song': '17', 'random': '0', 'state': 'play', 'xfade': '0', 'volume': '22', 'single': '0', 'time': '9:296', 'elapsed': '9.030', 'bitrate': '160'}
```

I agree its weird that mopidy does not give a nextsongid as it states in [their protocol](https://docs.mopidy.com/en/latest/modules/mpd/?highlight=nextsongid#mopidy.mpd.protocol.status.status) (perhaps there is something wrong with python-mpd2?). But arguably, it shouldn't have to give a "nextsongid" as it states it has a playlist (which in this case is the play queue) and plays song 17 of 34. And as long as the state is 'playing' then next can be sent as next on the last song will only tell the player to stop playing and return status stopped. (which I assume would be expected of all mpd's)

**Comment by eonpatapon** [comment]
If nextsongid is not present maybe we can check that songid < playlistlength ?

Wouldn't that work also ?

**Comment by subfusc** [comment]
No. If you have shuffle/random on, you can play the last song and still have a "next one"

**Comment by eonpatapon** [comment]
Right, but we have the state of random.
So I guess "songid < playlistlength or random == true" could work.

**Comment by subfusc** [comment]
you also have to take into account repeat[_one]. For a [chart](https://docs.mopidy.com/en/latest/modules/mpd/?highlight=nextsongid#mopidy.mpd.protocol.playback.next_)

If there is a desire to do any toggling on this, I would suggest: 

CanGoNext = state != 'stopped'
