### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by eonpatapon** [eonpatapon/mpDris2#69]
I'm thinking about doing a 0.7 release with the latest patches

WDYT @grawity ?

**Comment by grawity** [comment]
Sounds fine, if autotools still works after my 'fixes'... still waiting for a reply on #68, specifically.

**Comment by grawity** [comment]
As there don't seem to be any more bug reports, 0.7 would be good

**Comment by eonpatapon** [comment]
Done, thanks
