### ISSUE TITLE
The paused/playing notification isn’t terribly useful

### ISSUE THREAD

**Issue by nagisa** [eonpatapon/mpDris2#71]
![screenshot from 2015-12-23 00-39-50](https://cloud.githubusercontent.com/assets/679122/11967738/037710ea-a90e-11e5-9f15-98fa1b012f3d.png)

Is what being shown currently (one of the notifications is from mpDris2, another is from ario). Maybe it could instead show more useful information (since it is now showing the notification at all), e.g.

> **Music Player Daemon** Playing
> Track from Album by Artist

**Comment by grawity** [comment]
Somewhat improved in master, please test.

**Comment by nagisa** [comment]
Much better. Thanks!
