### ISSUE TITLE
Doesnt react to all actions asked from gnome-applet

### ISSUE THREAD

**Issue by lgnap** [eonpatapon/mpDris2#72]
The status of the mpd daemon works well and without any issue.
But it's impossible to do some actions on MPD server.

`gdbus monitor -e -d org.mpris.MediaPlayer2.mpd` returns nothing for any actions but works well when updating data to display coming from mpd (tested with an mpc on mpd host)

It's the returns from the --debug switch for any command (always the same)
```
2016-02-01 22:37:18,706 mpDris2 DEBUG: Socket event <flags G_IO_IN of type GIOCondition> on fd <__main__.MPDWrapper object at 0x7f41cb8f3550>
2016-02-01 22:37:18,706 mpDris2 DEBUG: Idle events: []
2016-02-01 22:37:18,707 mpDris2 DEBUG: Entered idle
``

**Comment by grawity** [comment]
Not sure what "gnome-applet" you're talking about. Do you mean something from extensions.gnome.org?

Try `dbus monitor --session` as well. (The gdbus tool's monitor mode is a little too specific.)

**Comment by lgnap** [comment]
Indeed I got more data with this command (I found the other command used in another ticket sorry)

![So these buttons](https://cloud.githubusercontent.com/assets/915876/12863014/1567ae64-cc71-11e5-9695-de9d31361cb8.png)


`method call time=1454718327.708547 sender=:1.15 -> destination=:1.46 serial=1729 path=/org/mpris/MediaPlayer2; interface=org.mpris.MediaPlayer2.Player; member=Next
error time=1454718327.709495 sender=:1.46 -> destination=:1.15 error_name=org.freedesktop.DBus.Python.TypeError reply_serial=1729
   string "Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/dbus/service.py", line 707, in _message_cb
    retval = candidate_method(self, *args, **keywords)
  File "/usr/local/bin/mpDris2", line 1042, in Next
    mpd_wrapper.next()
  File "/usr/local/bin/mpDris2", line 795, in fn
    return self.call(attr, *a, **kw)
  File "/usr/local/bin/mpDris2", line 802, in call
    was_idle = self.idle_leave()
  File "/usr/local/bin/mpDris2", line 417, in idle_leave
    self._fetch_object()
  File "/usr/local/bin/mpDris2", line 782, in _fetch_object
    return self.client._writecommand(*args)
TypeError: _writecommand() takes at least 2 arguments (1 given)
`

**Comment by grawity** [comment]
Which version of python-mpd do you have installed?

**Comment by grawity** [comment]
Try the version from Git, it should fix this.

**Comment by lgnap** [comment]
Thanks, it reacts now. Thank for the speed and resolution ;-)
I have another issue, but I'll open other ticket
