### ISSUE TITLE
mpd connection should be read from environment, not hardcoded localhost

### ISSUE THREAD

**Issue by tidux** [eonpatapon/mpDris2#93]
The MPD_HOST environment variable exists so client programs like mpDris2 can connect to daemons running on something other than localhost:6600.  I have some systems where mpd is bound to a specific non-localhost IPv4 or IPv6 address in order to enable network control, and mpDris2 can't connect to these systems without manually editing the script.  This is suboptimal.

**Comment by grawity** [comment]
Reading MPD_HOST from environment has been supported since 2011:

https://github.com/eonpatapon/mpDris2/blob/c8a764a006d5c9462879e7cff86ecd90cd8d5c19/mpDris2#L583-L594
