### ISSUE TITLE
Album art cover image sometimes appears too large.

### ISSUE THREAD

**Issue by doronbehar** [eonpatapon/mpDris2#94]
Here is example showing a notification completely covering the page:

![desktop 2017 09 10-17 03 29](https://user-images.githubusercontent.com/10998835/30249761-548bb586-964b-11e7-8946-db0ef591d7bb.png)

### Setup:

I use [`https://github.com/stefano-m/lua-media_player`](https://github.com/stefano-m/lua-media_player) to display notifications and to control my MPD instance in awesome-Wm. I was searching through the source code of [`https://github.com/stefano-m/lua-media_player`](https://github.com/stefano-m/lua-media_player) and couldn't find anything related to displaying album art or cover albums images.

I'm not sure here is the right place to ask, and not at the `lua-media_player` module, but would it be possible to configure `mpDris2` to display album art images in a defined fixed size?

**Comment by grawity** [comment]
mpDris2 does not _display_ anything; it only exports information for other programs (consumers) to use. Only the consumer itself (lua-media_player) knows what size it needs, so it should do its own resizing on display.

Besides that, there can be multiple consumers running at the same time (each of which would want a different cover size), as well as multiple _providers_ (each of which would need to be taught about resizing). So just making mpDris2 blindly resize the exported image is not going to satisfy anyone.

**Comment by doronbehar** [comment]
You are right, I should ask @stefano-m about it, thanks any way :)

**Comment by grawity** [comment]
Though, now that you mention it: track notifications _can_ be invoked by mpDris2 itself, if configured. That would have nothing to do with MPRIS, I guess.

But even in that case, it would be the job of the _notification daemon_ to shrink the provided image to fit. Again, many apps can show notifications, and only the notification daemon itself would know what size it accepts.
